services:
  app:
    container_name: blood_pressure
    build: .
    restart: unless-stopped
    init: true
    environment:
      TG_KEY: ${TG_KEY}
    volumes:
      - ./data/sqlite:/app/data/sqlite
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
